#this is my first assignment
print("My name is Mercy Cheptoo")
print("I love myself very much")
print("I am 21 years old")
print("I started learning python as a challenge to myself")
print("I am a 3rd student at KCA university")
print("I am such an intelligent girl")
print("I want to be a data scientist")
print("I want to be vey rich")
print("I want to work for the UN at some point in my life")
print("Coding is actually such a fun activity")
